apiVersion: apps/v1
kind: Deployment
metadata:
  name: txn-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: txn-svc
  template:
    metadata:
      labels:
        app: txn-svc
    spec:
      containers:
        - name: app
          image: txn-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: txn-config
            - secretRef:
                name: txn-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"


